[package]
name = "albus"
version = "0.1.0"
authors = ["Collided Scope <collidedscope+github@protonmail.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.9.1"
num-bigint = "0.3.1"
num-traits = "0.2.14"
